import { apiClient } from './client';
import { Alert, PaginatedResponse, SeverityLevel, AlertStatus } from '../types';
import { fetchOverviewMetrics } from './dashboard';

export interface AlertFilterParams {
  severity?: SeverityLevel | 'ALL';
  status?: AlertStatus | 'ALL';
  search?: string;
  page?: number;
  pageSize?: number;
}

export async function fetchAlerts(params: AlertFilterParams = {}): Promise<PaginatedResponse<Alert>> {
  try {
    const res = await apiClient.get('/alerts', { params });
    return res.data;
  } catch (err) {
    const overview = await fetchOverviewMetrics();
    let items = [...overview.recentAlerts];

    // Add extra mock items to demonstrate pagination & search
    items.push(
      {
        id: 'ALT-9860',
        title: 'Kubelet Unauthenticated Read Access',
        description: 'Read-only port 10255 exposed on worker node pool',
        severity: 'MEDIUM',
        status: 'OPEN',
        riskScore: 62,
        riskLevel: 'MEDIUM',
        cloudProvider: 'AWS',
        resourceType: 'EKS',
        resourceId: 'eks-node-302',
        timestamp: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
        remediationSteps: ['Disable read-only port in kubelet configuration'],
        affectedServices: ['EKS Control Plane'],
        assignedTo: 'SecOps Tier 2',
      },
      {
        id: 'ALT-9852',
        title: 'Database Password Leak in Git Commit',
        description: 'Plaintext DB URI found in public repository commit push',
        severity: 'CRITICAL',
        status: 'IN_PROGRESS',
        riskScore: 95,
        riskLevel: 'CRITICAL',
        cloudProvider: 'GitHub',
        resourceType: 'Repository',
        resourceId: 'org/backend-core',
        timestamp: new Date(Date.now() - 1000 * 60 * 700).toISOString(),
        remediationSteps: ['Rotate database user passwords', 'Revoke Git commit & scrub history'],
        affectedServices: ['GitHub Enterprise', 'PostgreSQL Cluster'],
        assignedTo: 'AppSec Lead',
      },
      {
        id: 'ALT-9840',
        title: 'CloudTrail Log Stream Disrupted',
        description: 'Audit log stream stop event recorded by root account',
        severity: 'HIGH',
        status: 'OPEN',
        riskScore: 88,
        riskLevel: 'HIGH',
        cloudProvider: 'AWS',
        resourceType: 'CloudTrail',
        resourceId: 'main-audit-trail',
        timestamp: new Date(Date.now() - 1000 * 60 * 1200).toISOString(),
        remediationSteps: ['Re-enable CloudTrail logging stream', 'Investigate root account activity'],
        affectedServices: ['AWS CloudTrail', 'SIEM Collector'],
        assignedTo: 'Incident Commander',
      }
    );

    if (params.severity && params.severity !== 'ALL') {
      items = items.filter((a) => a.severity === params.severity);
    }
    if (params.status && params.status !== 'ALL') {
      items = items.filter((a) => a.status === params.status);
    }
    if (params.search) {
      const q = params.search.toLowerCase();
      items = items.filter(
        (a) =>
          a.title.toLowerCase().includes(q) ||
          a.description.toLowerCase().includes(q) ||
          a.id.toLowerCase().includes(q) ||
          a.resourceId.toLowerCase().includes(q)
      );
    }

    const page = params.page || 1;
    const pageSize = params.pageSize || 10;
    const total = items.length;

    return {
      data: items,
      total,
      page,
      pageSize,
      totalPages: Math.ceil(total / pageSize),
    };
  }
}

export async function fetchAlertById(id: string): Promise<Alert | null> {
  try {
    const res = await apiClient.get(`/alerts/${id}`);
    return res.data;
  } catch (err) {
    const list = await fetchAlerts();
    const alert = list.data.find((a) => a.id === id);
    if (alert) return alert;

    return {
      id,
      title: `Alert ${id} Details`,
      description: 'Automated threat detection alert generated by Aegis Sentinel Real-time Engine.',
      severity: 'HIGH',
      status: 'OPEN',
      riskScore: 82,
      riskLevel: 'HIGH',
      cloudProvider: 'AWS',
      resourceType: 'EC2 / IAM',
      resourceId: `res-${id.toLowerCase()}-instance`,
      timestamp: new Date().toISOString(),
      remediationSteps: [
        'Isolate compromised workload using Security Group lockdown',
        'Revoke temporary AWS IAM credentials',
        'Trigger SOC Playbook #42 (Automated Containment)'
      ],
      affectedServices: ['Core API Server', 'User Database', 'Cache Layer'],
      assignedTo: 'SecOps Response Team',
    };
  }
}

export async function updateAlertStatus(id: string, status: AlertStatus): Promise<Alert> {
  try {
    const res = await apiClient.patch(`/alerts/${id}`, { status });
    return res.data;
  } catch (err) {
    const alert = await fetchAlertById(id);
    return { ...alert!, status };
  }
}
